// <auto-generated />
namespace MVC_Web_Forms.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class foruth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(foruth));
        
        string IMigrationMetadata.Id
        {
            get { return "202203200619227_foruth"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
